# Generated by Django 3.2.12 on 2022-04-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='tweeter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
