# Generated by Django 3.2.13 on 2022-04-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tweeter',
            field=models.URLField(blank=True),
        ),
    ]
