# Generated by Django 3.2.12 on 2022-04-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220404_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='tweeter',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
