# Generated by Django 3.2.13 on 2022-05-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tweeter',
            new_name='twitter',
        ),
    ]
