# Generated by Django 3.2.13 on 2022-05-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_tweeter_user_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forum_profile',
            field=models.URLField(blank=True),
        ),
    ]
