# Generated by Django 3.2.13 on 2022-05-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_forum_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='forum_profile',
            new_name='forum',
        ),
    ]
