# Generated by Django 3.2.13 on 2022-06-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='armPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('repo', models.CharField(max_length=50, null=True)),
                ('stable', models.CharField(max_length=50, null=True)),
                ('testing', models.CharField(max_length=50, null=True)),
                ('unstable', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('repo', models.CharField(max_length=50, null=True)),
                ('stable', models.CharField(max_length=50, null=True)),
                ('testing', models.CharField(max_length=50, null=True)),
                ('unstable', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
