# Generated by Django 3.2.14 on 2022-09-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_formfield_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='allowed_languages',
            field=models.BooleanField(default=False, help_text='Only allow German and English'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='min_message_characters',
            field=models.IntegerField(default=200, help_text='allowed characters'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='min_name_characters',
            field=models.IntegerField(default=7, help_text='allowed characters'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='no_html',
            field=models.BooleanField(default=False, help_text='Do not allow html'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='no_links',
            field=models.BooleanField(default=False, help_text='Do not allow links'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='only_bussiness_addresses',
            field=models.BooleanField(default=False, help_text='Only allow Bussiness Addresses in company contact'),
        ),
    ]
