# Generated by Django 4.0.10 on 2023-10-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
