# Generated by Django 3.2.14 on 2022-08-24 12:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0029_updatestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='category', max_length=20)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Docs Category',
                'verbose_name_plural': 'Docs Categories',
            },
        ),
        migrations.CreateModel(
            name='DocsListing',
            fields=[
                ('custompage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.custompage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.custompage',),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('custompage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.custompage')),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='docs.DocsCategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.custompage',),
        ),
    ]
