# Generated by Django 3.2.10 on 2022-01-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220123_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='body',
            new_name='content',
        ),
    ]
