# Generated by Django 3.2.12 on 2022-03-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpage_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author_description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
