# Generated by Django 3.2.13 on 2022-04-18 07:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerssponsors',
            name='content',
            field=wagtail.fields.StreamField([('partners', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Vendor', required=True)), ('description', wagtail.blocks.TextBlock(help_text='Short Vendor Description', required=True))]))], blank=True, null=True),
        ),
    ]
