# Generated by Django 3.2.13 on 2022-04-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_partnerssponsors_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='promotion_link',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promotion_url',
            field=models.URLField(blank=True),
        ),
    ]
