# Generated by Django 3.2.10 on 2022-01-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_blogindexpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='content',
        ),
    ]
