# Generated by Django 3.2.10 on 2022-01-26 19:37

import customblocks.blocks
from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_body_homepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('full_richtext', customblocks.blocks.RichtextBlock())], blank=True, null=True),
        ),
    ]
