# Generated by Django 3.2.13 on 2022-04-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220423_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='intro',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='donations',
            name='intro',
            field=models.TextField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='donations',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='intro',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='team',
            name='intro',
            field=models.TextField(blank=True, max_length=350),
        ),
    ]
