# Generated by Django 3.2.13 on 2022-04-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220423_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='footer_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='footer_intro',
        ),
    ]
