# Generated by Django 3.2.10 on 2022-01-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
