# Generated by Django 3.2.13 on 2022-04-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220426_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='arch_linux_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='aur_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='branches_intro',
            field=models.TextField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='features',
            name='calamares_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='common_settings_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='gnome_layout_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='gnome_layout_switcher_intro',
            field=models.TextField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='features',
            name='graphic_drivers_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='kernels_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='manjaro_layout_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='microsoft_office_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='msm_intro',
            field=models.TextField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='features',
            name='package_formats_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='pamac_intro',
            field=models.TextField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='features',
            name='skype_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='stable_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='testing_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='tilling_layout_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='traditional_layout_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='unstable_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='updates_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='web_app_manager_intro',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
