# Generated by Django 3.2.12 on 2022-03-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle',
        ),
    ]
