# Generated by Django 3.2.13 on 2022-04-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220428_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='aur_intro',
            field=models.TextField(blank=True, max_length=450),
        ),
        migrations.AlterField(
            model_name='features',
            name='calamares_intro',
            field=models.TextField(blank=True, max_length=450),
        ),
        migrations.AlterField(
            model_name='features',
            name='web_app_manager_intro',
            field=models.TextField(blank=True, max_length=450),
        ),
    ]
