# Generated by Django 3.2.12 on 2022-03-21 14:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0012_remove_homepage_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBlock',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.core.fields.StreamField([('productdetails', wagtail.core.blocks.StructBlock([('brand', wagtail.core.blocks.CharBlock()), ('model', wagtail.core.blocks.CharBlock()), ('cpu', wagtail.core.blocks.CharBlock()), ('screen', wagtail.core.blocks.CharBlock()), ('gpu', wagtail.core.blocks.CharBlock())]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
