# Generated by Django 3.2.13 on 2022-04-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220428_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='branches_intro',
            field=models.TextField(blank=True, max_length=450),
        ),
        migrations.AlterField(
            model_name='features',
            name='intro',
            field=models.TextField(blank=True, max_length=450),
        ),
    ]
