# Generated by Django 3.2.12 on 2022-03-22 09:55

import customblocks.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0013_productblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('richtext', customblocks.blocks.RichtextBlock()), ('product_details', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Vendor', required=True)), ('description', wagtail.core.blocks.CharBlock(help_text='Very Short Vendor Description', required=True)), ('product_details', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('Brand', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('Model', wagtail.core.blocks.CharBlock(max_length=80, required=True)), ('Description', wagtail.core.blocks.TextBlock(max_length=250, required=True)), ('button_url', wagtail.core.blocks.URLBlock(required=True))])))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductBlock',
        ),
    ]
