# Generated by Django 3.2.13 on 2022-05-02 09:53

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_features_branches_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='promotion_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promotion_url',
        ),
        migrations.AddField(
            model_name='homepage',
            name='affiliate',
            field=wagtail.fields.StreamField([('promotion', wagtail.blocks.StructBlock([('promotion', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(required=True)), ('url', wagtail.blocks.URLBlock(required=True)), ('background', wagtail.images.blocks.ImageChooserBlock(help_text='Vendor Background Image', required=True))])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='budgie_description',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='budgie_notes',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='cinnamon_description',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='cinnamon_notes',
            field=models.TextField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='gnome_description',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='gnome_notes',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='i3_description',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='i3_notes',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='mate_description',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='mate_notes',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='plasma_description',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='plasma_notes',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='sway_description',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='sway_notes',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='xfce_description',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='xfce_notes',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
