# Generated by Django 3.2.13 on 2022-05-02 10:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220502_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='affiliate',
            field=wagtail.fields.StreamField([('promotion', wagtail.blocks.StructBlock([('promotion', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(required=True)), ('url', wagtail.blocks.URLBlock(required=True)), ('background', wagtail.images.blocks.ImageChooserBlock(help_text='Vendor Background Image', required=True))]))]))], blank=True, null=True),
        ),
    ]
