# Generated by Django 3.2.13 on 2022-05-02 11:16

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_homepage_affiliate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='affiliate',
            field=wagtail.core.fields.StreamField([('promotion', wagtail.core.blocks.StructBlock([('promotion', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=True)), ('url', wagtail.core.blocks.URLBlock(required=True)), ('background', wagtail.images.blocks.ImageChooserBlock(help_text='Vendor Background Image', required=True))]))]))], blank=True, null=True),
        ),
    ]
