# Generated by Django 3.2.12 on 2022-03-29 10:42

import customblocks.blocks
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='content',
            field=wagtail.core.fields.StreamField([('richtext', customblocks.blocks.RichtextBlock())], blank=True, null=True),
        ),
    ]
