# Generated by Django 3.2.12 on 2022-03-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_donations_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
