# Generated by Django 3.2.13 on 2022-05-04 09:49

import customblocks.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20220503_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='content',
            field=wagtail.fields.StreamField([('product_details', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Vendor', required=True)), ('description', wagtail.blocks.CharBlock(help_text='Very Short Vendor Description', required=True)), ('vendor_logo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('product_details', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('certified', wagtail.blocks.BooleanBlock(help_text='if the hardware is Manjaro certified', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('model', wagtail.blocks.CharBlock(max_length=100, required=True)), ('processor', wagtail.blocks.CharBlock(max_length=100, required=True)), ('screen', wagtail.blocks.CharBlock(max_length=100, required=True)), ('memory', wagtail.blocks.CharBlock(max_length=100, required=True)), ('storage', wagtail.blocks.CharBlock(max_length=100, required=True)), ('ports', wagtail.blocks.CharBlock(max_length=150, required=True)), ('graphics', wagtail.blocks.CharBlock(max_length=100, required=False)), ('description', wagtail.blocks.TextBlock(max_length=650, required=False)), ('button_url', wagtail.blocks.URLBlock(required=True))])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('richtext', customblocks.blocks.RichtextBlock()), ('product_details', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Vendor', required=True)), ('description', wagtail.blocks.CharBlock(help_text='Very Short Vendor Description', required=True)), ('vendor_logo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('product_details', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('certified', wagtail.blocks.BooleanBlock(help_text='if the hardware is Manjaro certified', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('model', wagtail.blocks.CharBlock(max_length=100, required=True)), ('processor', wagtail.blocks.CharBlock(max_length=100, required=True)), ('screen', wagtail.blocks.CharBlock(max_length=100, required=True)), ('memory', wagtail.blocks.CharBlock(max_length=100, required=True)), ('storage', wagtail.blocks.CharBlock(max_length=100, required=True)), ('ports', wagtail.blocks.CharBlock(max_length=150, required=True)), ('graphics', wagtail.blocks.CharBlock(max_length=100, required=False)), ('description', wagtail.blocks.TextBlock(max_length=650, required=False)), ('button_url', wagtail.blocks.URLBlock(required=True))])))]))], blank=True, null=True),
        ),
    ]
