# Generated by Django 3.2.12 on 2022-03-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_donations_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='intro',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
