# Generated by Django 3.2.12 on 2022-04-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_donations_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='feature_one',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
