# Generated by Django 3.2.13 on 2022-05-05 13:19

import customblocks.blocks
from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20220504_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloads',
            name='budgie_image',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='budgie_notes',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='cinnamon_image',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='cinnamon_notes',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='gnome_image',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='gnome_notes',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='i3_image',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='i3_notes',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='mate_image',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='mate_notes',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='plasma_image',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='plasma_notes',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='sway_image',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='sway_notes',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='xfce_image',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='xfce_notes',
        ),
        migrations.AddField(
            model_name='downloads',
            name='minimal_description',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
        migrations.AddField(
            model_name='downloads',
            name='plasma_mobile_description',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
        migrations.AddField(
            model_name='downloads',
            name='posh_description',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='content',
            field=wagtail.fields.StreamField([('product_details', wagtail.blocks.StructBlock([('product_details', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('certified', wagtail.blocks.BooleanBlock(help_text='if the hardware is Manjaro certified', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='images must be 500x375 with space around the space determinates the image size', required=True)), ('model', wagtail.blocks.CharBlock(max_length=100, required=True)), ('processor', wagtail.blocks.CharBlock(max_length=100, required=True)), ('screen', wagtail.blocks.CharBlock(max_length=100, required=False)), ('memory', wagtail.blocks.CharBlock(max_length=100, required=True)), ('storage', wagtail.blocks.CharBlock(max_length=100, required=True)), ('ports', wagtail.blocks.CharBlock(max_length=150, required=True)), ('graphics', wagtail.blocks.CharBlock(max_length=100, required=False)), ('description', wagtail.blocks.TextBlock(max_length=650, required=False)), ('button_url', wagtail.blocks.URLBlock(required=True))])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('richtext', customblocks.blocks.RichtextBlock()), ('product_details', wagtail.blocks.StructBlock([('product_details', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('certified', wagtail.blocks.BooleanBlock(help_text='if the hardware is Manjaro certified', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='images must be 500x375 with space around the space determinates the image size', required=True)), ('model', wagtail.blocks.CharBlock(max_length=100, required=True)), ('processor', wagtail.blocks.CharBlock(max_length=100, required=True)), ('screen', wagtail.blocks.CharBlock(max_length=100, required=False)), ('memory', wagtail.blocks.CharBlock(max_length=100, required=True)), ('storage', wagtail.blocks.CharBlock(max_length=100, required=True)), ('ports', wagtail.blocks.CharBlock(max_length=150, required=True)), ('graphics', wagtail.blocks.CharBlock(max_length=100, required=False)), ('description', wagtail.blocks.TextBlock(max_length=650, required=False)), ('button_url', wagtail.blocks.URLBlock(required=True))])))]))], blank=True, null=True),
        ),
    ]
