# Generated by Django 3.2.13 on 2022-05-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20220505_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloads',
            old_name='posh_description',
            new_name='phosh_description',
        ),
    ]
