# Generated by Django 3.2.12 on 2022-04-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220405_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='manjaro_description',
            new_name='manjaro_intro',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='partners_description',
            new_name='partners_intro',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='shells_description',
            new_name='shells_intro',
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_intro',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
