# Generated by Django 3.2.13 on 2022-05-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_posh_description_downloads_phosh_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloads',
            old_name='community_spins_intro',
            new_name='community_intro',
        ),
        migrations.RenameField(
            model_name='downloads',
            old_name='arm_spins_intro',
            new_name='manjaro_arm_team_intro',
        ),
        migrations.RenameField(
            model_name='downloads',
            old_name='team_spins_intro',
            new_name='manjaro_team_intro',
        ),
        migrations.AlterField(
            model_name='downloads',
            name='docker_intro',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
    ]
