# Generated by Django 3.2.12 on 2022-04-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20220405_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloads',
            name='arm_spins_title',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='community_spins_title',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='docker_title',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='manual_title',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='team_spins_title',
        ),
    ]
