# Generated by Django 3.2.12 on 2022-04-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20220405_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
