# Generated by Django 3.2.12 on 2022-04-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0027_downloads_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='xfce_description',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='downloads',
            name='xfce_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='xfce_notes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
