# Generated by Django 3.2.12 on 2022-04-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20220405_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloads',
            name='xfce_notes',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
