# Generated by Django 3.2.12 on 2022-04-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0029_alter_downloads_xfce_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='budgie_description',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='downloads',
            name='budgie_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='budgie_notes',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='downloads',
            name='cinnamon_description',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='downloads',
            name='cinnamon_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='cinnamon_notes',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='downloads',
            name='gnome_description',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='downloads',
            name='gnome_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='gnome_notes',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='downloads',
            name='i3_description',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='downloads',
            name='i3_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='i3_notes',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='downloads',
            name='mate_description',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='downloads',
            name='mate_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='mate_notes',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='downloads',
            name='plasma_description',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='downloads',
            name='plasma_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='plasma_notes',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='downloads',
            name='sway_description',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='downloads',
            name='sway_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='sway_notes',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
