# Generated by Django 3.2.14 on 2022-08-29 10:06

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_updatestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='affiliate',
            field=wagtail.fields.StreamField([('promotion', wagtail.blocks.StructBlock([('promotion', wagtail.blocks.StructBlock([('hidden', wagtail.blocks.BooleanBlock(help_text='hide this promotion', required=False)), ('text', wagtail.blocks.CharBlock(required=True)), ('url', wagtail.blocks.URLBlock(required=True)), ('background', wagtail.images.blocks.ImageChooserBlock(help_text='Vendor Background Image', required=True))]))]))], blank=True, null=True),
        ),
    ]
