# Generated by Django 3.2.12 on 2022-04-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20220405_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloads',
            name='answer_one',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='answer_three',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='answer_two',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='arm_spins_intro',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='community_spins_intro',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='docker_intro',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='manual_intro',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='team_spins_intro',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
