# Generated by Django 3.2.14 on 2022-08-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_homepage_affiliate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloads',
            name='intro',
            field=models.TextField(blank=True, default='', max_length=700),
        ),
    ]
