# Generated by Django 3.2.14 on 2022-09-07 12:06

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_downloads_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='shells_intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='shells_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='shells_url',
        ),
        migrations.AddField(
            model_name='homepage',
            name='software',
            field=wagtail.fields.StreamField([('software', wagtail.blocks.StructBlock([('software', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('hidden', wagtail.blocks.BooleanBlock(default=False, help_text='hide this promotion', required=False)), ('url', wagtail.blocks.URLBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))]))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='software_intro',
            field=models.TextField(blank=True, max_length=350),
        ),
    ]
