# Generated by Django 3.2.14 on 2022-09-14 14:53

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20220907_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='reviews',
            field=wagtail.core.fields.StreamField([('reviews', wagtail.core.blocks.StructBlock([('video', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('hidden', wagtail.core.blocks.BooleanBlock(default=False, help_text='hide this video', required=False)), ('embed_code', wagtail.core.blocks.CharBlock(required=True)), ('description', wagtail.core.blocks.TextBlock(required=True))]))]))], blank=True, null=True),
        ),
    ]
