# Generated by Django 3.2.16 on 2022-11-14 10:52

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_features_pamac_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='affiliate',
            field=wagtail.fields.StreamField([('promotion', wagtail.blocks.StructBlock([('promotion', wagtail.blocks.StructBlock([('hidden', wagtail.blocks.BooleanBlock(help_text='hide this promotion', required=False)), ('model', wagtail.blocks.CharBlock(required=True)), ('url', wagtail.blocks.URLBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Vendor Image', required=True)), ('description', wagtail.blocks.TextBlock())]))]))], blank=True, null=True),
        ),
    ]
