# Generated by Django 3.2.12 on 2022-04-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20220407_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsors',
            name='content',
        ),
    ]
