# Generated by Django 3.2.12 on 2022-04-07 11:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_sponsors_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='content',
            field=wagtail.core.fields.StreamField([('sponsor', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Vendor', required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Short Vendor Description', required=True)), ('details', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))])))]))], blank=True, null=True),
        ),
    ]
