# Generated by Django 3.2.16 on 2022-11-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20221121_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloads',
            name='answer_one',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='answer_three',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='answer_two',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='manual_intro',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='question_one',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='question_three',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='question_two',
        ),
    ]
