# Generated by Django 3.2.12 on 2022-04-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_sponsors_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='intro',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
    ]
