# Generated by Django 3.2.16 on 2022-12-13 12:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0037_auto_20221129_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, default='', max_length=450)),
                ('_videos', wagtail.fields.StreamField([('video', wagtail.blocks.StructBlock([('video', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('hidden', wagtail.blocks.BooleanBlock(default=False, help_text='hide this video', required=False)), ('embed_code', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True))]))]))], blank=True, null=True)),
                ('keywords', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
