# Generated by Django 3.2.12 on 2022-04-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20220407_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='description',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='partners',
            name='intro',
            field=models.TextField(blank=True, default='', max_length=80),
        ),
    ]
