# Generated by Django 3.2.12 on 2022-04-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20220407_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='description',
        ),
        migrations.AlterField(
            model_name='partners',
            name='intro',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
    ]
