# Generated by Django 3.2.12 on 2022-04-08 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0005_blogpage_main_color'),
        ('home', '0040_auto_20220408_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blogpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puput.blogpage')),
                ('keywords', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('puput.blogpage',),
            managers=[
                ('extra', django.db.models.manager.Manager()),
            ],
        ),
    ]
