# Generated by Django 3.2.16 on 2023-02-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20230201_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='intro',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
