# Generated by Django 3.2.16 on 2023-02-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_donations_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='intro',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
