# Generated by Django 3.2.16 on 2023-02-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_donations_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='intro',
        ),
    ]
