# Generated by Django 3.2.12 on 2022-04-09 11:17

import customblocks.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20220408_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='content',
            field=wagtail.core.fields.StreamField([('product_details', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Vendor', required=True)), ('description', wagtail.core.blocks.CharBlock(help_text='Very Short Vendor Description', required=True)), ('vendor_logo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('product_details', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('Brand', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('Model', wagtail.core.blocks.CharBlock(max_length=80, required=True)), ('Description', wagtail.core.blocks.TextBlock(max_length=250, required=True)), ('button_url', wagtail.core.blocks.URLBlock(required=True))])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('richtext', customblocks.blocks.RichtextBlock()), ('product_details', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Vendor', required=True)), ('description', wagtail.core.blocks.CharBlock(help_text='Very Short Vendor Description', required=True)), ('vendor_logo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('product_details', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('Brand', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('Model', wagtail.core.blocks.CharBlock(max_length=80, required=True)), ('Description', wagtail.core.blocks.TextBlock(max_length=250, required=True)), ('button_url', wagtail.core.blocks.URLBlock(required=True))])))]))], blank=True, null=True),
        ),
    ]
