# Generated by Django 3.2.16 on 2023-02-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_remove_donations_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='backers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donations',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donations',
            name='yearly_goal',
            field=models.IntegerField(default=0),
        ),
    ]
