# Generated by Django 3.2.18 on 2023-03-15 16:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('home', '0045_auto_20230220_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sponsoring_manjaro_as_a_business', models.TextField(blank=True)),
                ('sponsoring_manjaro_as_a_individual', models.TextField(blank=True)),
                ('content', wagtail.fields.StreamField([('sponsors', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock(required=False)), ('description', wagtail.blocks.TextBlock(help_text='Short Vendor Description', required=False)), ('vendor_logo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('category', wagtail.blocks.TextBlock(required=True))]))], blank=True, null=True, use_json_field=True)),
                ('platinum', models.IntegerField(blank=True, default=0, help_text='montly ammount')),
                ('gold', models.IntegerField(blank=True, default=0, help_text='montly ammount')),
                ('silver', models.IntegerField(blank=True, default=0, help_text='montly ammount')),
                ('bronze', models.IntegerField(blank=True, default=0, help_text='montly ammount')),
                ('outstanding', models.IntegerField(blank=True, default=0, help_text='montly ammount')),
                ('amazing', models.IntegerField(blank=True, default=0, help_text='montly ammount')),
                ('keywords', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
