# Generated by Django 3.2.18 on 2023-03-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20230220_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='partners_intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='partners_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='partners_url',
        ),
    ]
