# Generated by Django 3.2.18 on 2023-04-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20230321_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='features',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='partnerssponsors',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='team',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='updatestatus',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='intro',
        ),
    ]
