# Generated by Django 3.2.12 on 2022-04-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20220409_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='intro',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
    ]
