# Generated by Django 3.2.18 on 2023-04-20 16:12

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20230406_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='old_contributer',
            field=wagtail.fields.StreamField([('old_contributer', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True)), ('picture', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
