# Generated by Django 3.2.12 on 2022-04-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_team_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloads',
            name='description',
        ),
    ]
