# Generated by Django 4.0.10 on 2023-09-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_team_old_contributer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='affiliate',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='software',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='software_intro',
        ),
    ]
