# Generated by Django 4.2.4 on 2024-01-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_remove_homepage_affiliate_remove_homepage_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='backers',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='yearly_goal',
        ),
    ]
