# Generated by Django 3.2.12 on 2022-04-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_rename_partners_partnerssponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='intro',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
    ]
