# Generated by Django 3.2.13 on 2022-06-09 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='aarch64',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('arch', models.CharField(max_length=50, null=True)),
                ('repo', models.CharField(max_length=20, null=True)),
                ('stable', models.CharField(max_length=50, null=True)),
                ('testing', models.CharField(max_length=50, null=True)),
                ('unstable', models.CharField(max_length=50, null=True)),
                ('last_modified', models.CharField(max_length=20, null=True)),
                ('group', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=120, null=True)),
                ('packager', models.CharField(max_length=100, null=True)),
                ('builddate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lastModified',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arch', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('repo', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, default='', max_length=350)),
                ('keywords', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='x86_64',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('arch', models.CharField(max_length=50, null=True)),
                ('repo', models.CharField(max_length=20, null=True)),
                ('stable', models.CharField(max_length=50, null=True)),
                ('testing', models.CharField(max_length=50, null=True)),
                ('unstable', models.CharField(max_length=50, null=True)),
                ('last_modified', models.CharField(max_length=20, null=True)),
                ('group', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=120, null=True)),
                ('packager', models.CharField(max_length=100, null=True)),
                ('builddate', models.DateField(null=True)),
            ],
        ),
    ]
