# Generated by Django 3.2.13 on 2022-06-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aarch64',
            options={'ordering': ('name', 'repo')},
        ),
        migrations.AlterModelOptions(
            name='x86_64',
            options={'ordering': ('name', 'repo')},
        ),
    ]
