# Generated by Django 3.2.13 on 2022-06-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armpackage',
            name='last_update',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='last_update',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
