# Generated by Django 3.2.13 on 2022-06-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('architecture', models.IntegerField()),
                ('name', models.CharField(max_length=100, null=True)),
                ('arch', models.CharField(max_length=50, null=True)),
                ('repo', models.CharField(max_length=20, null=True)),
                ('stable', models.CharField(max_length=50, null=True)),
                ('testing', models.CharField(max_length=50, null=True)),
                ('unstable', models.CharField(max_length=50, null=True)),
                ('last_modified', models.CharField(max_length=20, null=True)),
                ('group', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=120, null=True)),
                ('packager', models.CharField(max_length=100, null=True)),
                ('builddate', models.DateField(null=True)),
            ],
            options={
                'ordering': ('name', 'repo'),
            },
        ),
        migrations.DeleteModel(
            name='aarch64',
        ),
        migrations.DeleteModel(
            name='x86_64',
        ),
        migrations.CreateModel(
            name='aarch64',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('compare.packagemodel',),
        ),
        migrations.CreateModel(
            name='x86_64',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('compare.packagemodel',),
        ),
    ]
