# Generated by Django 3.2.13 on 2022-06-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_auto_20220611_1333'),
        ('compare', '0002_auto_20220611_1837'),
    ]

    operations = [
    ]
