# Generated by Django 3.2.13 on 2022-06-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_auto_20220607_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='armpackage',
            name='builddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='armpackage',
            name='group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='armpackage',
            name='packager',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='armpackage',
            name='url',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='builddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='packager',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='url',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='armpackage',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='armpackage',
            name='repo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='repo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
