# Generated by Django 3.2.14 on 2022-08-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_auto_20220616_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastmodified',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
