# Generated by Django 3.2.14 on 2022-08-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_alter_lastmodified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
