# Generated by Django 3.2.14 on 2022-08-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_alter_packagemodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
