# Generated by Django 3.2.18 on 2023-04-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0005_alter_packagemodel_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='intro',
        ),
    ]
