# Generated by Django 3.2.13 on 2022-04-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category_title',
            field=models.CharField(help_text='Visible name of the menu, footer menus only', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(help_text='Options: top left, top right, footer one, footer two, footer three, footer four', max_length=50, null=True),
        ),
    ]
