# Generated by Django 3.2.14 on 2022-08-01 13:08

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20220423_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='submenu',
            field=wagtail.core.fields.StreamField([('submenu_item', wagtail.core.blocks.StructBlock([('submenu_item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, max_length=50, null=True, required=True)), ('url', wagtail.core.blocks.CharBlock(blank=True, max_length=500)), ('open_in_new_tab', wagtail.core.blocks.BooleanBlock(required=False))]))]))], blank=True, null=True),
        ),
    ]
