# Generated by Django 3.2.14 on 2022-08-31 15:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menuitem_submenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='submenu',
            field=wagtail.core.fields.StreamField([('submenu_item', wagtail.core.blocks.StructBlock([('submenu_item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, max_length=50, null=True, required=True)), ('icon', wagtail.core.blocks.CharBlock(blank=True, max_length=50)), ('description', wagtail.core.blocks.CharBlock(blank=True, max_length=150)), ('url', wagtail.core.blocks.CharBlock(default='<i class="fa-brands fa-fonticons"></i>', max_length=500)), ('open_in_new_tab', wagtail.core.blocks.BooleanBlock(required=False))]))]))], blank=True, null=True),
        ),
    ]
