# Generated by Django 3.2.12 on 2022-03-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_auto_20220323_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
