# Generated by Django 3.2.12 on 2022-03-23 11:16

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0014_menu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='s',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
