# Generated by Django 3.2.12 on 2022-03-23 11:20

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0015_menu_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='s',
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='HOOO'),
        ),
    ]
